version: "3.9"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: filemanagement-azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    environment:
      AZURITE_BLOB_CORS: "*"
      AZURITE_QUEUE_CORS: "*"
      AZURITE_TABLE_CORS: "*"
    volumes:
      - azurite_data:/data
    command: >
       azurite --loose --location /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0

  azurite-init: 
    image: mcr.microsoft.com/azure-cli
    depends_on: 
      - azurite
    command: 
      - sh
      - -c
      - | 
          echo 'Waiting for Azurite...'
          sleep 2
          az storage container create \
            --name firstcontainer \
            --account-name devstoreaccount1 \
            --account-key Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OU= \
            --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OU=;BlobEndpoint=http://azurite:10000/devstoreaccount1;"

volumes:
  azurite_data: